"../../Win32\OGL Release\LSFbxConverter.exe" -file "Amy.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Ashley.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Aston.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Audi A4.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Audi A6.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Beam Kirby.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Big Donut.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Biohazard 5.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Blue Falcon.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Bowser's Castle.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "BMW.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "BMW X6.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "BMW Z4.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "C-17 Globemaster.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Cali.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Cayman.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Charizard.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "city_all.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Char01.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Chevy.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Cobra.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Colin.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Corvette.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Cruiser.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "DB5.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "DBR9.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "DeDeDe.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Dodge Challenger.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Dodge.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Evo.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "F14.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Fang.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Fenix.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Ferrari.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Fiat.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "GigaBowser.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Glut.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Gorem_U_01_pa.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "GT.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Guido.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Hilux.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Hmv.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Hole Planet.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Hover.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Hunter.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "janken_02_idle.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "jumpwoman.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Mansion Planet.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Mario Circuit.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Merc.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Mercedes.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "mikubest.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Nissan.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Noire.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "P149.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "PC-21.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Peach.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Peach Beach.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Peach Blossom.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Petey Prianha.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Peugot.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Polaras.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "QuadBot.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Rainbow Road.FBX"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "RX7.FBX"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Samus.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Saleen.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "simple_quadbot2.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Spartan.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Spitfire.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Terrain.FBX"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Thunderbord.FBX"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Toad Harbor.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "ToonGirl.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Toyota.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "TugBoat.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "UAZ.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "UH60.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Viper.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Woman.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Yoshi's Island.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Zelda.fbx"
"../../Win32\OGL Release\LSFbxConverter.exe" -file "Zo6.fbx"